application: ionpmf
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
# Endpoints handler
- url: /_ah/spi/.*
  script: ipmf.application

- url: /
  static_files: index.html
  upload: index\.html

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /iPMFLogo\.png
  static_files: iPMFLogo.png
  upload: iPMFLogo\.png

- url: /js
  static_dir: js

- url: /css
  static_dir: css


libraries:
- name: endpoints
  version: "latest"

- name: MySQLdb
  version: "latest"
